version: '2'
services:
  mqtt:
    image: ghcr.io/metbosch/mosquitto-docker-letsencrypt-auth:master
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 80:80
    environment:
      - DOMAIN=mqtt.example.org
      - EMAIL=info@example.org
    volumes:
      - ./mosquitto/conf/:/mosquitto/conf
      - ./mosquitto/log/:/mosquitto/log
      - ./letsencrypt:/etc/letsencrypt
    restart: always
